# Multi-stage Dockerfile for ClubConnect (Next.js + pnpm)
FROM node:20-alpine AS builder
WORKDIR /app

# Install build tools and pnpm
RUN apk add --no-cache python3 make g++ git && \
    corepack enable && corepack prepare pnpm@latest --activate

# Copy dependency definitions first for caching
COPY package.json pnpm-lock.yaml ./

# Install dependencies (allow lockfile update in CI/build environments)
RUN pnpm install --no-frozen-lockfile

# Copy source
COPY . .

# Supabase public env vars must be present at build time (inlined by Next.js compiler)
ARG NEXT_PUBLIC_SUPABASE_URL
ARG NEXT_PUBLIC_SUPABASE_ANON_KEY
ENV NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL
ENV NEXT_PUBLIC_SUPABASE_ANON_KEY=$NEXT_PUBLIC_SUPABASE_ANON_KEY

RUN pnpm build

FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV PORT=3000
# Next.js binds to HOSTNAME (not HOST)
ENV HOSTNAME=0.0.0.0

# standalone output is self-contained; static assets must be copied separately
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/public ./public

EXPOSE 3000

# server.js is generated by Next.js standalone output
CMD ["node", "server.js"]
